name: k6 performance test

on:
  push:
    branches: [ main ]

jobs:
  teste_de_carga_k6:
    name: Perfomance test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install k6 by homebrew
        run: brew install k6

      - name: Install Node.js dependencies
        run: npm install

      - name: k6 run
        run: k6 run ./tests/scenarios/auth/loginTest.js
    
    
  
  
