name: k6 performance test

on:
  push:
    branches: [ main ]

jobs:
  teste_de_carga_k6:
    name: Perfomance test
    runs-on: ubuntu-latest
    
    steps:
      - name: Install k6
        run: apt-get install k6

      - name: k6 run
        run: k6 run ./tests/scenarios/auth/loginTest.js
    
    
  
  
